/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badges: typeof import('./components/Badges.vue')['default']
    BlockQuote: typeof import('./components/BlockQuote.vue')['default']
    LanguageBlock: typeof import('./components/LanguageBlock.vue')['default']
    LanguageSelect: typeof import('./components/LanguageSelect.vue')['default']
  }
}
